# Generated by Django 5.0.6 on 2024-05-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0002_rename_tables_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='route',
            field=models.CharField(choices=[('LIS-TMS', 'LIS-TMS'), ('TMS-LIS', 'TMS-LIS')], default='TMS-LIS', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='route',
            field=models.CharField(choices=[('LIS-TMS', 'LIS-TMS'), ('TMS-LIS', 'TMS-LIS')], default='LIS-TMS', max_length=7),
        ),
    ]
