# Generated by Django 5.0.6 on 2024-05-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0003_table_route_alter_flight_route'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('date', 'route')},
        ),
    ]
