# Generated by Django 5.0.6 on 2024-05-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0004_alter_flight_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
