# Generated by Django 5.0.6 on 2024-05-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0005_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='route',
            field=models.CharField(choices=[('PT', 'Portugal'), ('ST', 'São Tomé e Príncipe'), ('BR', 'Brasil'), ('GB', 'Guiné-Bissau'), ('MZ', 'moçambique'), ('CV', 'cabo Verde')], default='BR', max_length=2),
        ),
    ]
