# Generated by Django 5.0.6 on 2024-05-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0007_alter_airport_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='route',
            field=models.CharField(choices=[('PT', 'Portugal'), ('ST', 'São Tomé e Príncipe'), ('BR', 'Brasil'), ('GB', 'Guiné-Bissau'), ('MZ', 'Moçambique'), ('CV', 'Cabo Verde'), ('AG', 'Angola')], default='BR', max_length=2),
        ),
    ]
