# Generated by Django 5.0.6 on 2024-05-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0008_alter_airport_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='acronym',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
