# Generated by Django 5.0.6 on 2024-05-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0009_alter_airport_acronym_alter_airport_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='route',
            new_name='country',
        ),
    ]
