# Generated by Django 5.0.6 on 2024-05-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0010_rename_route_airport_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='route',
        ),
        migrations.AddField(
            model_name='table',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
