# Generated by Django 5.0.6 on 2024-05-19 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0011_remove_table_route_table_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(choices=[('PT', 'Portugal'), ('ST', 'São Tomé e Príncipe'), ('BR', 'Brasil'), ('GB', 'Guiné-Bissau'), ('MZ', 'Moçambique'), ('CV', 'Cabo Verde'), ('AG', 'Angola')], max_length=2)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='airport',
            name='country',
        ),
        migrations.AddField(
            model_name='airport',
            name='country_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fly.country'),
        ),
    ]
