# Generated by Django 5.0.6 on 2024-05-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0012_country_remove_airport_country_airport_country_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='acronym',
            field=models.CharField(choices=[('PT', 'Portugal'), ('ST', 'São Tomé e Príncipe'), ('BR', 'Brasil'), ('GB', 'Guiné-Bissau'), ('MZ', 'Moçambique'), ('CV', 'Cabo Verde'), ('AG', 'Angola')], max_length=2, unique=True),
        ),
    ]
