# Generated by Django 5.0.6 on 2024-05-19 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0013_alter_country_acronym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='country_2',
            new_name='country',
        ),
    ]
