# Generated by Django 5.0.6 on 2024-05-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0015_alter_airport_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='fly/airport/images/'),
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='fly/country/images/'),
        ),
    ]
