# Generated by Django 5.0.6 on 2024-05-26 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0017_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='route',
            field=models.CharField(choices=[('LIS-TMS', 'LIS-TMS'), ('TMS-LIS', 'TMS-LIS'), ('LIS-OXB', 'LIS-OXB'), ('OXB-LIS', 'OXB-LIS'), ('VPY-LIS', 'VPY-LIS'), ('LIS-VPY', 'LIS-VPY')], default='LIS-TMS', max_length=7),
        ),
    ]
