# Generated by Django 5.0.6 on 2024-05-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0019_alter_flight_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='route',
            field=models.CharField(choices=[('LIS-TMS', 'LIS-TMS'), ('TMS-LIS', 'TMS-LIS'), ('LIS-OXB', 'LIS-OXB'), ('OXB-LIS', 'OXB-LIS'), ('VPY-LIS', 'VPY-LIS'), ('LIS-VPY', 'LIS-VPY'), ('LAD-LIS', 'LAD-LIS'), ('LIS-LAD', 'LIS-LAD'), ('BSB-LIS', 'BSB-LIS'), ('LIS-BSB', 'LIS-BSB'), ('RAI-LIS', 'RAI-LIS'), ('LIS-RAI', 'LIS-RAI')], default='LIS-TMS', max_length=7),
        ),
    ]
