# Generated by Django 5.0.6 on 2024-06-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0022_alter_contact_email_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
