# Generated by Django 5.0.6 on 2024-06-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0023_remove_contact_email_remove_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquire',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
