# Generated by Django 5.0.6 on 2024-06-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0024_enquire_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquire',
            name='country_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
