# Generated by Django 5.0.6 on 2024-07-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0026_country_alter_enquire_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
