# Generated by Django 5.0.6 on 2024-07-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0028_alter_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
