# Generated by Django 5.0.6 on 2024-08-28 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0030_airline_flight_request_remove_enquire_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='City',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='country',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='country_to',
        ),
        migrations.AddField(
            model_name='flight',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='fly.city'),
        ),
        migrations.AddField(
            model_name='flight',
            name='city_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_to', to='fly.city'),
        ),
    ]
