# Generated by Django 5.0.6 on 2024-08-28 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0031_rename_country_city_remove_flight_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arlines', to='fly.airline'),
        ),
    ]
