# Generated by Django 5.0.6 on 2024-08-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0032_flight_airline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('file', models.FileField(upload_to='marvoa/prices')),
            ],
        ),
    ]
