# Generated by Django 5.0.6 on 2024-08-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0033_trush'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateField(),
        ),
    ]
