# Generated by Django 5.0.6 on 2024-08-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0034_alter_flight_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trush',
            name='file',
        ),
        migrations.AddField(
            model_name='trush',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('airline', 'date', 'city')},
        ),
    ]
