# Generated by Django 5.0.6 on 2024-08-28 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0035_remove_trush_file_trush_text_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('airline', 'date', 'city', 'final_price')},
        ),
    ]
