# Generated by Django 5.0.6 on 2024-08-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0036_alter_flight_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='base_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
