# Generated by Django 5.0.6 on 2024-08-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0037_alter_flight_base_price_alter_flight_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trush',
            name='file',
            field=models.FileField(null=True, upload_to='marvoa/prices'),
        ),
    ]
