# Generated by Django 5.0.6 on 2024-08-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0038_trush_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
