# Generated by Django 5.0.6 on 2024-08-30 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0039_alter_flight_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Enquiriment',
        ),
    ]
