# Generated by Django 5.0.6 on 2024-08-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0040_rename_request_enquiriment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiriment',
            name='status',
            field=models.CharField(choices=[('T', 'Talked'), ('P', 'Pendent'), ('D', 'Completed')], default='P', max_length=1),
        ),
    ]
