# Generated by Django 5.0.6 on 2024-08-30 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0041_enquiriment_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquiriment',
            new_name='Enquire',
        ),
    ]
