# Generated by Django 5.0.6 on 2024-09-08 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0042_rename_enquiriment_enquire'),
    ]

    operations = [
        migrations.AddField(
            model_name='trush',
            name='city_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_from_trush', to='fly.city'),
        ),
        migrations.AddField(
            model_name='trush',
            name='city_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_to_trush', to='fly.city'),
        ),
    ]
