# Generated by Django 5.0.6 on 2024-09-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0044_menssenger_users_moviments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviments',
            name='name',
        ),
        migrations.AlterField(
            model_name='moviments',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
