# Generated by Django 5.0.6 on 2024-09-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0045_remove_moviments_name_alter_moviments_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='menssenger',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Moviments',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
