# Generated by Django 5.0.6 on 2024-09-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0046_menssenger_details_delete_moviments_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='marvoa/prices')),
            ],
        ),
    ]
