# Generated by Django 5.0.6 on 2024-09-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0047_law'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='file',
        ),
        migrations.AddField(
            model_name='law',
            name='current_law',
            field=models.FileField(null=True, upload_to='kandja/law'),
        ),
        migrations.AddField(
            model_name='law',
            name='cv_code',
            field=models.FileField(null=True, upload_to='kandja/law'),
        ),
        migrations.AddField(
            model_name='law',
            name='new_code',
            field=models.FileField(null=True, upload_to='kandja/law'),
        ),
    ]
