# Generated by Django 5.0 on 2025-09-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0049_country_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='image_from',
            field=models.FileField(null=True, upload_to='fly/images'),
        ),
    ]
