# Generated by Django 5.0 on 2025-09-30 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0050_flight_image_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trushs', to='fly.trush'),
        ),
    ]
