# Generated by Django 5.0 on 2025-10-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fly', '0051_flight_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='trush',
            name='inverse',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
