# Generated by Django 5.0.6 on 2024-11-17 11:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nike', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('DBS', 'DBS')], max_length=3)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('prove', models.FileField(upload_to='camaramz/fund/proves/')),
                ('date', models.DateField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fund.person')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fund.person')),
                ('referenced_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='all_references', to='fund.person')),
            ],
        ),
    ]
