# Generated by Django 5.0.6 on 2024-11-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact',
            field=models.CharField(default=900000, max_length=10),
            preserve_default=False,
        ),
    ]
