# Generated by Django 5.0.6 on 2024-11-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_person_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
