# Generated by Django 5.0.6 on 2024-11-20 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_alter_person_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('file', models.FileField(null=True, upload_to='camaramz/fund/contacts/')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='currency',
            field=models.CharField(choices=[('EUR', 'EUR'), ('GBP', 'GBP'), ('DBS', 'DBS')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='nike',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='payment_day',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='person',
            name='value',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=8),
        ),
    ]
