# Generated by Django 5.0.6 on 2025-02-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productimage_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('identity', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'color')},
        ),
    ]
