# Generated by Django 5.0.6 on 2025-02-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_match_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('identity', 'product')},
        ),
    ]
