# Generated by Django 5.0.6 on 2025-02-02 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_match_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='store.product'),
        ),
    ]
