# Generated by Django 5.0.6 on 2025-02-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_order_product_order_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='images',
            new_name='image',
        ),
    ]
