"""
Django settings for camaramz project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "corsheaders",
    "djoser",
    "certificates",
    "cmz",
    # "blog",
    "ormed",
    "cecab",
    "nanehouse",
    "fly",
    # "fund",
    "setup",
    "core",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "camaramz.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "camaramz.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "core.User"
# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = "/static/"
# STATICFILES_STORAGE = ('whitenoise.storage.CompressedManifestStaticFilesStorage')
STATIC_ROOT = os.path.join(BASE_DIR, "static")


# MEDIA_URL = "media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATICFILES_LOCATION = 'static'
MEDIAFILES_LOCATION = 'media'

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),

    "COERCE_DECIMAL_TO_STRING": False,
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend']
}

# uid = "MQ"
# token = "afnd93-8d1799decda7137bbf57c047ed33ee86"

SITE_NAME = "Camâra Mé-Zóchi"
DJOSER = {
    "SET_PASSWORD_RETYPE": True,
    "SET_USERNAME_RETYPE": True,
    # the reset link

    "PASSWORD_RESET_CONFIRM_URL": "auth/reset-password/{uid}/{token}",
    "PASSWORD_RESET_CONFIRM_RETYPE": True,
    "PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND": True,
    "SERIALIZERS": {
        "user_create": "core.serializers.UserCreateSerializer",
        "user": "core.serializers.UserSerializer",
        "current_user": "core.serializers.UserSerializer",
        "set_password_retype": "core.serializers.SetPasswordRetypeSerializer",
        "set_username": "core.serializers.SetUsernameSerializer",
        "password_reset": "core.serializers.SendEmailResetSerializer",
        "password_reset_confirm_retype": "core.serializers.PasswordResetConfirmRetypeSerializer",
        # 'token_create': 'apps.accounts.serializers.CustomTokenCreateSerializer',
    },
    # 'EMAIL': {
    #     'password_reset': 'your_app.views.PasswordResetEmail',
    # },

}


SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("JWT",),
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

APPEND_SLASH = True
# ALLOWED_HOSTS = ['127.0.0.1']
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_HEADERS = ["*"]
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
# CORS_ALLOWED_ORIGINS = ["http://localhost:3000","http://127.0.0.1:3000"]
# If this is used then `CORS_ALLOWED_ORIGINS` will not have any effect
CORS_ALLOW_ALL_ORIGINS = True
# If this is used, then not need to use `CORS_ALLOW_ALL_ORIGINS = True`
CORS_ALLOWED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000"]
CORS_ALLOWED_ORIGIN_REGEXES = [
    "http://localhost:3000", "http://127.0.0.1:3000"]


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "file": {
            "class": "logging.FileHandler",
            "filename": "general.log",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "": {
            "handlers": ["console", "file"],
            "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO"),
        }
    },
    "formatters": {
        "verbose": {
            "format": "{asctime} ({levelname}) - {name} - {message}",
            "style": "{",
        }
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"


ADMINS = [("Ramos", "admin@hotmail.com")]

PRICE_PARCEL_BY_KG = 15
PRICE_FLIGTH_BY_KG = 3.3

AWS_ACCESS_KEY_ID = 'AKIA2QHYRZDKXSR7F2KK'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'bm-edmilbe-bucket'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# storages.backends.s3boto3.S3Boto3Storage


STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME


STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, STATICFILES_LOCATION)
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)


MOVED = 872

EMAIL_HOST_USER = "edmilbe@gmail.com"
EMAIL_HOST_PASSWORD = "vpawkftfpryiqaly"

WEBSITES = ["CMZ", "ORMED", "CECAB", "NANEHOUSE"]


EMAILS = {
    WEBSITES[0]: {
        "EMAIL": "edmilbe@gmail.com",
        "PASSWORD":  "vpawkftfpryiqaly",
        "WEBSITE":  "https://camaramz-cc67c4aaa69f.herokuapp.com/",
        "LOGO":  "https://www.camaramezochi.st/files/stp/camara2.png",

    },
    WEBSITES[1]: {
        "EMAIL": "ormedstp@gmail.com",
        "PASSWORD":  "tbsrqlvuphlkqkce",
        "WEBSITE":  "https://ormedstp.herokuapp.com/",
        "LOGO":  "https://ormedstp.herokuapp.com/images/logo-2.png",

    },
    WEBSITES[2]: {
        "EMAIL": "direcaocecab@gmail.com",
        "PASSWORD":  "pfyp czdj ihkz ghik",
        "WEBSITE":  "https://www.cecab.st/",
        "LOGO":  "https://www.cecab.st/images/logo.png",

    },
    WEBSITES[3]: {
        "EMAIL": EMAIL_HOST_USER,
        "PASSWORD":  EMAIL_HOST_PASSWORD,
        "WEBSITE":  "https://www.edmilbe.pro/",
        "LOGO":  "https://edmilbe-fa58f9b99040.herokuapp.com/light/assets/imgs/header/profile.jpg",

    },
}


