# Generated by Django 4.2.7 on 2024-03-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_cecab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='district',
        ),
        migrations.RemoveField(
            model_name='associationimages',
            name='associaton',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Pathner',
        ),
        migrations.RemoveField(
            model_name='postdocument',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postvideos',
            name='post',
        ),
        migrations.DeleteModel(
            name='Spot',
        ),
        migrations.RemoveField(
            model_name='team',
            name='role',
        ),
        migrations.DeleteModel(
            name='YearGols',
        ),
        migrations.DeleteModel(
            name='Association',
        ),
        migrations.DeleteModel(
            name='AssociationImages',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostDocument',
        ),
        migrations.DeleteModel(
            name='PostImages',
        ),
        migrations.DeleteModel(
            name='PostVideos',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
