# Generated by Django 4.2.1 on 2023-06-10 08:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AddressTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_phone', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('initial', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('date_issue', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CertificateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('goal', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('code', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255)),
                ('post_code', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.country')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='address', to='certificates.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Fligth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Cancelled'), ('P', 'Pendent'), ('M', 'Delivered'), ('A', 'Arrived')], default='P', max_length=1)),
                ('payment_status', models.CharField(choices=[('C', 'Completed'), ('P', 'Pendent'), ('M', 'Delivered')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departure_at', models.DateTimeField()),
                ('arrive_at', models.DateTimeField()),
                ('number', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('arrive_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fligths_to', to='certificates.airport')),
            ],
        ),
        migrations.CreateModel(
            name='FligthsCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IDType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('text', models.TextField()),
                ('sent', models.BooleanField(blank=True, default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('C', 'Collected'), ('M', 'Shipping'), ('P', 'Pendent'), ('D', 'Delivered')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date_collection', models.DateTimeField(null=True)),
                ('address_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.customeraddress')),
                ('colaborator_deliver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaborator_deliver', to='certificates.colaborator')),
                ('colaborator_get', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colaborator_get', to='certificates.colaborator')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='certificates.customer')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Weigth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.county')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.town')),
            ],
        ),
        migrations.CreateModel(
            name='ShippimentFligth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('colaborator_from', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='shippiment_from', to='certificates.colaborator')),
                ('colaborator_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shippiment_to', to='certificates.colaborator')),
                ('fligth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shippiment_fligths', to='certificates.fligth')),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shippiment_fligths', to='certificates.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('house_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('street', models.CharField(max_length=255)),
                ('post_code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivers', to='certificates.country')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to='certificates.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('id_number', models.CharField(max_length=255)),
                ('id_issue_local', models.CharField(max_length=255)),
                ('id_issue_date', models.DateField()),
                ('id_expire_date', models.DateField()),
                ('father_name', models.CharField(max_length=255)),
                ('mother_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('L', 'Living together'), ('V', 'Viuvo'), ('D', 'Divorcied')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person', to='certificates.house')),
                ('birth_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birth_person', to='certificates.country')),
                ('birth_county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.county')),
                ('birth_street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.street')),
                ('birth_town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.town')),
                ('id_issue_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_issue_person', to='certificates.country')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.idtype')),
            ],
        ),
        migrations.AddField(
            model_name='parcel',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='certificates.receiver'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='weigth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels', to='certificates.weigth'),
        ),
        migrations.AddField(
            model_name='house',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.street'),
        ),
        migrations.AddField(
            model_name='fligth',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.fligthscompany'),
        ),
        migrations.AddField(
            model_name='fligth',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fligths', to='certificates.customer'),
        ),
        migrations.AddField(
            model_name='fligth',
            name='departure_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fligths_from', to='certificates.airport'),
        ),
        migrations.AddField(
            model_name='fligth',
            name='weigth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fligths', to='certificates.weigth'),
        ),
    ]
