# Generated by Django 4.2.1 on 2023-06-10 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='county',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.country'),
        ),
        migrations.AddField(
            model_name='colaborator',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='colaborators', to='certificates.customer'),
        ),
        migrations.AddField(
            model_name='certificatetitle',
            name='certificate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetypes'),
        ),
        migrations.AddField(
            model_name='certificatedata',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificate'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='main_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_person_certificates', to='certificates.person'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='secondary_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_person_certificates', to='certificates.person'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.certificatetitle'),
        ),
        migrations.AddField(
            model_name='cart',
            name='country_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_country_from', to='certificates.country'),
        ),
        migrations.AddField(
            model_name='cart',
            name='country_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_country_to', to='certificates.country'),
        ),
        migrations.AddField(
            model_name='cart',
            name='weigth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.weigth'),
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.country'),
        ),
        migrations.AddField(
            model_name='addressto',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_to', to='certificates.cart'),
        ),
        migrations.AddField(
            model_name='addressfrom',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_from', to='certificates.cart'),
        ),
    ]
