# Generated by Django 4.2.7 on 2023-11-04 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='certificate',
            name='type1',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='type1',
            new_name='type_id1',
        ),
        migrations.AddField(
            model_name='street',
            name='county',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.county'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_issue',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='main_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='main_person_certificates', to='certificates.person'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('C', 'Concluído'), ('F', 'Incorrecto'), ('P', 'Pendente'), (
                'R', 'Revisto'), ('A', 'Archived')], default='P', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='text',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to='certificates.certificatetitle'),
        ),
        migrations.AlterField(
            model_name='certificatetitle',
            name='certificate_type',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetypes'),
        ),
        migrations.AlterField(
            model_name='certificatetitle',
            name='type_price',
            field=models.DecimalField(
                decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetypes',
            name='gender',
            field=models.CharField(
                choices=[('o', 'o'), ('a', 'a')], default='o', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='person', to='certificates.house'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='id_issue_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='id_issue_person', to='certificates.country'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='person_nationality', to='certificates.country'),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
