# Generated by Django 4.2.7 on 2023-11-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_rename_type1_certificate_type_id1_street_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='type_id1',
            field=models.IntegerField(null=True),
        ),
    ]
