# Generated by Django 4.2.7 on 2023-11-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_alter_certificate_type_id1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
