# Generated by Django 4.2.1 on 2023-06-16 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_remove_addressto_cart_remove_airport_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_county',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_street',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_town',
        ),
        migrations.AlterField(
            model_name='person',
            name='id_issue_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_issue_person', to='certificates.institution'),
        ),
        migrations.AlterField(
            model_name='street',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.town'),
        ),
        migrations.AlterField(
            model_name='town',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='certificates.county'),
        ),
        migrations.CreateModel(
            name='PersonBirthAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birth_person_address', to='certificates.country')),
                ('birth_county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birth_person_address', to='certificates.county')),
                ('birth_street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birth_person_address', to='certificates.street')),
                ('birth_town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birth_person_address', to='certificates.town')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='birth_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='certificates.personbirthaddress'),
            preserve_default=False,
        ),
    ]
