# Generated by Django 4.2.7 on 2023-11-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='atestado_state',
            field=models.IntegerField(null=True, default=1),
        ),
        migrations.AlterField(
            model_name='certificatesimpleperson',
            name='gender',
            field=models.CharField(
                choices=[('M', 'Male'), ('F', 'Femal')], max_length=1),
        ),
    ]
