# Generated by Django 4.2.7 on 2023-11-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '00042_add_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bi_nasc_loc',
            field=models.IntegerField(null=True, default=1),
        ),

    ]
