# Generated by Django 4.2.7 on 2023-11-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '00040_alter_certificatesimpleperson_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='birth_day',
            field=models.IntegerField(null=True, default=1),
        ),
        migrations.AddField(
            model_name='certificate',
            name='birth_month',
            field=models.IntegerField(null=True, default=1),
        ),
        migrations.AddField(
            model_name='certificate',
            name='birth_year',
            field=models.IntegerField(null=True, default=1),
        ),

    ]
