# Generated by Django 4.2.7 on 2023-11-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '00043_add_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id_issue_day',
            field=models.IntegerField(null=True, default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='id_issue_month',
            field=models.IntegerField(null=True, default=1),
        ),
        migrations.AddField(
            model_name='person',
            name='id_issue_year',
            field=models.IntegerField(null=True, default=1),
        ),

    ]
