# Generated by Django 4.2.7 on 2023-11-04 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_alter_customer_level'),
    ]

    operations = [

        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='obs',
            field=models.TextField(null=True),
        ),
    ]
