# Generated by Django 4.2.1 on 2023-06-16 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_remove_person_birth_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='person_nationality', to='certificates.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personbirthaddress',
            name='birth_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='birth_person_address', to='certificates.country'),
            preserve_default=False,
        ),
    ]
