# Generated by Django 4.2.1 on 2023-06-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_person_nationality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.house'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificatedata',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.certificate'),
        ),
        migrations.AlterField(
            model_name='certificatedata',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.house'),
        ),
    ]
