# Generated by Django 4.2.7 on 2023-11-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_alter_certificate_status_alter_customer_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='atestado_state',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('C', 'Concluído'), ('F', 'Incorrecto'), (
                'P', 'Pendente'), ('R', 'Revisto'), ('A', 'Archived')], default='P', max_length=1),
        ),
    ]
