# Generated by Django 4.2.1 on 2023-06-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_certificate_house_alter_certificatedata_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
