# Generated by Django 4.2.2 on 2023-06-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_alter_certificate_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='father_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
