# Generated by Django 4.2.2 on 2023-06-18 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_alter_person_father_name_alter_person_mother_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institution',
            new_name='Instituition',
        ),
    ]
