# Generated by Django 4.2.2 on 2023-06-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_alter_person_gender_certificatesimpleperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateSinglePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetitle')),
            ],
        ),
    ]
