# Generated by Django 4.2.2 on 2023-06-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_certificatesingleperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('in_plural', models.CharField(max_length=255)),
                ('in_plural_mix', models.CharField(max_length=255)),
            ],
        ),
    ]
