# Generated by Django 4.2.2 on 2023-06-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0012_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
