# Generated by Django 4.2.2 on 2023-06-19 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0013_parents_gender'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parents',
            new_name='Parent',
        ),
        migrations.CreateModel(
            name='CertificateSimpleFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.parent')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetitle')),
            ],
        ),
    ]
