# Generated by Django 4.2.2 on 2023-06-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0014_rename_parents_parent_certificatesimplefamily'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CertificateSimpleFamily',
            new_name='CertificateSimpleParent',
        ),
    ]
