# Generated by Django 4.2.2 on 2023-06-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0015_rename_certificatesimplefamily_certificatesimpleparent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatesimpleparent',
            name='gender',
        ),
    ]
