# Generated by Django 4.2.2 on 2023-06-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0016_remove_certificatesimpleparent_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='degree',
            field=models.IntegerField(default=1),
        ),
    ]
