# Generated by Django 4.2.2 on 2023-06-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0017_parent_degree'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_number', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('date_used', models.DateField()),
                ('date_of_deth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
    ]
