# Generated by Django 4.2.2 on 2023-06-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0018_coval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coval',
            name='date_of_deth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coval',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='coval',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coval',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
