# Generated by Django 4.2.2 on 2023-06-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0019_alter_coval_date_of_deth_alter_coval_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coval',
            name='square',
            field=models.IntegerField(default=1),
        ),
    ]
