# Generated by Django 4.2.2 on 2023-06-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0020_coval_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coval',
            name='square',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
        ),
    ]
