# Generated by Django 4.2.2 on 2023-06-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0022_cemiterio'),
    ]

    operations = [
        migrations.AddField(
            model_name='coval',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
