# Generated by Django 4.2.2 on 2023-06-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0024_biuldingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biuldingtype',
            name='prefix',
            field=models.CharField(default='', max_length=255),
        ),
    ]
