# Generated by Django 4.2.2 on 2023-06-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0025_alter_biuldingtype_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biuldingtype',
            name='prefix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
