# Generated by Django 4.2.2 on 2023-06-19 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0026_alter_biuldingtype_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biuldingtype',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.house'),
        ),
    ]
