# Generated by Django 4.2.2 on 2023-06-19 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0027_alter_biuldingtype_prefix_alter_certificate_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='coval',
            name='selled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CovalSalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coval', models.CharField(max_length=255)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.person')),
            ],
        ),
    ]
