# Generated by Django 4.2.2 on 2023-06-19 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0028_coval_selled_covalsalles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covalsalles',
            name='coval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='certificates.coval'),
        ),
    ]
