# Generated by Django 4.2.2 on 2023-06-19 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0029_alter_covalsalles_coval'),
    ]

    operations = [
        migrations.AddField(
            model_name='coval',
            name='cemiterio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='certificates.cemiterio'),
        ),
    ]
