# Generated by Django 4.2.2 on 2023-06-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0031_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificates.certificatetitle')),
            ],
        ),
    ]
