# Generated by Django 4.2.2 on 2023-06-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0032_certificatedate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificatedate',
            old_name='data',
            new_name='date',
        ),
    ]
