# Generated by Django 4.2.2 on 2023-06-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0033_rename_data_certificatedate_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ifen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='certificatetypes',
            name='gender',
            field=models.CharField(choices=[('o', 'o'), ('a', 'a')], default='o', max_length=1),
        ),
    ]
