# Generated by Django 4.2.2 on 2023-06-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0034_ifen_certificatetypes_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifen',
            name='size',
            field=models.IntegerField(),
        ),
    ]
