# Generated by Django 4.2.2 on 2023-06-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0035_alter_ifen_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/certificates'),
        ),
    ]
