# Generated by Django 4.2.2 on 2023-06-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0036_certificate_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetitle',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificatetypes',
            name='slug',
            field=models.SlugField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='camaramz/certificates/certificates'),
        ),
    ]
