# Generated by Django 4.2.7 on 2023-11-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '00046_add_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='birth_day',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='birth_month',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='birth_year',
        ),
        migrations.AlterField(
            model_name='person',
            name='bi_estado',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='bi_nasc_loc',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='bi_sexo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_month',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_year',
            field=models.IntegerField(null=True),
        ),
    ]
