# Generated by Django 4.2.7 on 2023-11-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0047_remove_certificate_birth_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
