# Generated by Django 4.2.7 on 2023-11-04 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0049_alter_person_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, default=django.db.models.deletion.SET_NULL, null=True),
        ),
    ]
