# Generated by Django 4.2.7 on 2023-11-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0050_alter_person_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
    ]
