# Generated by Django 4.2.7 on 2023-11-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0051_remove_person_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id_expire_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id_issue_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='person',
            name='status',
        ),
    ]
