# Generated by Django 4.2.7 on 2023-11-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0052_remove_person_gender_remove_person_id_expire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_address',
        ),
    ]
