# Generated by Django 4.2.7 on 2023-11-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0053_remove_person_birth_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id_issue_country',
        ),
    ]
