# Generated by Django 4.2.7 on 2023-11-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0054_remove_person_id_issue_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='status',
        ),
    ]
