# Generated by Django 4.2.7 on 2023-11-04 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0055_remove_certificate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='status',
            field=models.CharField(choices=[('C', 'Concluído'), ('F', 'Incorrecto'), ('P', 'Pendente'), ('R', 'Revisto'), ('A', 'Archived')], default='P', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='certificates.personbirthaddress'),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, default=django.db.models.deletion.SET_NULL, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='id_expire_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='id_issue_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_issue_person', to='certificates.country'),
        ),
        migrations.AddField(
            model_name='person',
            name='id_issue_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_nationality', to='certificates.country'),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('M', 'Married'), ('S', 'Single'), ('L', 'Living together'), ('V', 'Viuvo'), ('D', 'Divorcied')], max_length=1, null=True),
        ),
    ]
