# Generated by Django 4.2.7 on 2023-11-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0056_certificate_status_person_birth_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
