# Generated by Django 4.2.7 on 2023-11-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0058_alter_certificate_id_alter_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
