# Generated by Django 4.2.7 on 2024-03-25 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmz', '0002_alter_messages_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='whatsapp',
            new_name='email',
        ),
    ]
