# Generated by Django 5.1.7 on 2025-05-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmz', '0005_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_cmz_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_social_service',
            field=models.BooleanField(default=False),
        ),
    ]
