# Generated by Django 5.1.7 on 2025-06-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmz', '0006_post_is_cmz_service_post_is_social_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Front',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('picture', models.FileField(upload_to='camaramz/front/images/')),
            ],
        ),
    ]
