# Generated by Django 5.1.7 on 2025-06-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmz', '0007_front'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(null=True, upload_to='camaramz/team/images/')),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('name', 'role')},
            },
        ),
    ]
