# Generated by Django 5.1.7 on 2025-07-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmz', '0008_assembly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('text_file', models.FileField(upload_to='camaramz/docs/documents/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('year', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ExtraDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('text_file', models.FileField(upload_to='camaramz/posts/documents/')),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('text_file', models.FileField(upload_to='camaramz/docs/documents/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('text_file', models.FileField(upload_to='camaramz/docs/documents/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('year', models.DateTimeField()),
            ],
        ),
    ]
