# Generated by Django 5.1.7 on 2025-07-01 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmz', '0009_budget_extradoc_laws_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='camaramz/extras/images/')),
                ('extra_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='cmz.extradoc')),
            ],
        ),
    ]
