# Generated by Django 5.1.7 on 2025-07-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmz', '0010_extraimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laws',
            new_name='Law',
        ),
    ]
