# Generated by Django 5.1.7 on 2025-07-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmz', '0011_rename_laws_law'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Law',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='budget',
            name='type',
            field=models.CharField(choices=[('B', 'Budget'), ('R', 'Report'), ('L', 'Law')], default='B', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
