# Generated by Django 5.1.7 on 2025-07-01 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmz', '0012_delete_law_delete_report_budget_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='year_real',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
