# Generated by Django 5.1.7 on 2025-07-01 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmz', '0013_budget_year_real'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='year',
        ),
    ]
