# Generated by Django 5.1.7 on 2025-07-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmz', '0014_remove_budget_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='year_real',
            new_name='year',
        ),
    ]
