# Generated by Django 5.1.7 on 2025-07-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmz', '0015_rename_year_real_budget_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='extradoc',
            name='picture',
            field=models.FileField(null=True, upload_to='camaramz/posts/images/'),
        ),
    ]
