# Generated by Django 4.2.4 on 2023-08-11 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informations', to='blog.service'),
        ),
        migrations.AlterField(
            model_name='secreatarysection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secreatary_sections', to='blog.section'),
        ),
    ]
