# Generated by Django 4.2.4 on 2023-08-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_information_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='picture',
            field=models.FileField(null=True, upload_to='camaramz/services/images/'),
        ),
    ]
