# Generated by Django 4.2.4 on 2023-08-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_service_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='Através desse seviço, estarás habilitado para ...'),
        ),
    ]
