# Generated by Django 4.2.4 on 2023-08-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_service_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='email',
        ),
        migrations.AddField(
            model_name='messages',
            name='whatsapp',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
