# Generated by Django 4.2.7 on 2024-03-24 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_messages_email_messages_whatsapp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagestour',
            name='tour',
        ),
        migrations.RemoveField(
            model_name='information',
            name='service',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postdocument',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostFile',
        ),
        migrations.RemoveField(
            model_name='postimages',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postvideos',
            name='post',
        ),
        migrations.RemoveField(
            model_name='secreatarysection',
            name='secretary',
        ),
        migrations.RemoveField(
            model_name='secreatarysection',
            name='section',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='team',
            name='role',
        ),
        migrations.DeleteModel(
            name='ImagesTour',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostDocument',
        ),
        migrations.DeleteModel(
            name='PostImages',
        ),
        migrations.DeleteModel(
            name='PostVideos',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='SecreatarySection',
        ),
        migrations.DeleteModel(
            name='Secretary',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
    ]
