# Generated by Django 5.1.7 on 2025-04-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cecab', '0002_remove_association_president_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
