# Generated by Django 5.1.7 on 2025-04-22 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ground.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sells', to='ground.customer'),
            preserve_default=False,
        ),
    ]
