# Generated by Django 5.1.7 on 2025-04-22 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0003_expend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expend',
            new_name='Expense',
        ),
    ]
