# Generated by Django 5.1.7 on 2025-04-22 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0004_rename_expend_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='destine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expends', to='ground.destine'),
        ),
    ]
