# Generated by Django 5.1.7 on 2025-04-23 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0005_destine_alter_expense_destine'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ground.client'),
        ),
    ]
