# Generated by Django 5.1.7 on 2025-04-23 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ground', '0006_payment_is_refund_alter_payment_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_refund',
        ),
        migrations.AddField(
            model_name='payment',
            name='from_destine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ground.destine'),
        ),
    ]
