# Generated by Django 5.0 on 2026-02-10 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BespokeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.CharField(max_length=255, unique=True)),
                ('image', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bespoketour_customer', to=settings.AUTH_USER_MODEL)),
                ('profile_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bespoketour.profiletype')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bespoke_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bespoketour.bespoketag')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bespoketour.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bespoke_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bespoketour.bespoketag')),
                ('profile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bespoketour.profiletype')),
            ],
        ),
    ]
