# Generated by Django 5.0 on 2026-02-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bespoketour', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profiletag',
            unique_together={('profile_type', 'bespoke_tag')},
        ),
    ]
