# Generated by Django 5.0 on 2026-02-10 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespoketour', '0002_alter_profiletag_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to='bespoketour.profiletype'),
        ),
        migrations.AlterField(
            model_name='profiletag',
            name='bespoke_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tag', to='bespoketour.bespoketag'),
        ),
        migrations.AlterField(
            model_name='profiletag',
            name='profile_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tag', to='bespoketour.profiletype'),
        ),
    ]
