# Generated by Django 5.0 on 2026-02-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespoketour', '0003_alter_customer_profile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiletag',
            name='bespoke_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tags', to='bespoketour.bespoketag'),
        ),
        migrations.AlterField(
            model_name='profiletag',
            name='profile_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_tags', to='bespoketour.profiletype'),
        ),
    ]
