# Generated by Django 5.0 on 2026-02-11 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespoketour', '0004_alter_profiletag_bespoke_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customertag',
            name='bespoke_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tags', to='bespoketour.bespoketag'),
        ),
        migrations.AlterField(
            model_name='customertag',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tags', to='bespoketour.customer'),
        ),
    ]
