# Generated by Django 5.0 on 2026-02-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespoketour', '0005_alter_customertag_bespoke_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to='bespoketour.profiletype'),
        ),
    ]
