# Generated by Django 5.0 on 2026-02-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespoketour', '0006_alter_customer_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiletype',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=2),
        ),
    ]
